In [1]:
from tensorflow.keras.models import load_model
model2=load_model("books_model.h5")

In [31]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv("books.csv")

In [33]:
df.head()

,id,isbn,isbn13,name,num_pages,language,genre,edition,year,author,author_rating,average_rating,ratings_count,impressions,clicks,level
0,1,1597496553,9781597496551,The Basics of Hacking and Penetration Testing:...,159,english,ethical hacking,1,2011,Patrick Engebretson,3.94,3.92,670,0,0,beginner
1,2,521880378,9780521880374,Advanced Data Structures,456,english,data structures,1,2008,Peter Brass,4.29,4.26,27,0,0,advanced
2,3,3,3,"Data Structures, Automation & Problem Solving,...",135,english,data structures,1,2015,R.M.Z. Trigo,3.03,3.33,12,0,0,intermediate
3,4,4,4,Python & Algorithms 2.0 A Guide to Learn how t...,244,english,python,2,2014,Marina Wahl,3.00,3.00,1,0,0,beginner
4,5,1484237323,9781484237328,Applied Natural Language Processing with Pytho...,158,english,machine learning,1,2018,Taweh Beysolow II,2.83,3.50,17,0,0,intermediate

In [34]:
df_new=df[['id','average_rating','author_rating','ratings_count','year','edition','impressions','clicks']]

In [35]:
df_new

,id,average_rating,author_rating,ratings_count,year,edition,impressions,clicks
0,1,3.92,3.94,670,2011,1,0,0
1,2,4.26,4.29,27,2008,1,0,0
2,3,3.33,3.03,12,2015,1,0,0
3,4,3.00,3.00,1,2014,2,0,0
4,5,3.50,2.83,17,2018,1,0,0
5,6,2.27,2.67,45,2017,1,0,0
6,7,3.61,3.58,32,2014,1,0,0
7,8,3.00,3.29,91,2018,1,0,0
8,9,3.30,3.66,10,2006,1,0,0
9,10,3.67,4.25,6,2017,1,0,0
10,11,4.50,4.50,100,2016,1,0,0
11,12,3.71,3.76,7,2011,3,0,0
12,13,3.86,3.77,126,1996,2,0,0
13,14,4.00,3.76,15,2011,3,0,0
14,15,4.09,3.92,99,2013,1,0,0
15,16,4.09,4.26,11,2018,1,0,0
16,17,4.50,4.50,100,2014,1,0,0
17,18,3.11,3.78,19,2007,1,0,0
18,19,4.13,4.13,732,2011,2,0,0
19,20,3.81,4.02,21,2010,1,0,0
20,21,3.52,3.77,29,2014,4,0,0
21,22,4.04,4.00,97,2003,2,0,0
22,23,3.50,4.28,3,2011,1,0,0
23,24,4.50,4.50,100,2016,1,0,0
24,25,3.83,3.92,254,2005,6,0,0
25,26,3.50,3.50,10,2016,1,0,0
26,27,4.50,4.50,100,2018,1,0,0
27,28,3.84,3.84,390,2016,1,0,0
28,29,3.25,2.91,4,2015,1,0,0
29,30,3.38,3.40,16,2012,1,0,0
30,31,1.00,3.29,1,2018,1,0,0
31,32,4.00,4.00,13,2017,1,0,0
32,33,3.00,3.00,2,2019,1,0,0
33,34,4.00,3.92,2,2008,1,0,0
34,35,4.07,3.92,160,2013,1,0,0
35,36,4.07,3.92,160,2013,2,0,0
36,37,4.00,3.94,98,2010,2,0,0
37,38,3.53,3.50,15,1999,1,0,0
38,39,4.34,4.34,1290,2016,1,0,0
39,40,3.35,3.47,20,2016,1,0,0
40,41,3.90,3.94,452,2003,1,0,0
41,42,3.92,3.94,283,2013,2,0,0
42,43,4.31,4.31,35,2016,2,0,0
43,44,3.41,3.44,22,2011,2,0,0
44,45,4.33,4.33,3,2018,1,0,0
45,46,3.58,3.58,57,2018,1,0,0
46,47,4.13,4.21,63,2005,2,0,0
47,48,4.44,4.07,16,2015,1,0,0
48,49,3.53,3.30,15,2014,1,0,0
49,50,4.16,4.16,1752,2013,1,0,0
50,51,3.82,3.82,102,2017,1,0,0
51,52,4.00,4.00,2,2014,1,0,0
52,53,3.50,3.79,8,2016,1,0,0
53,54,3.14,3.45,7,2015,1,0,0
54,55,4.20,4.22,5,2016,1,0,0
55,56,4.63,4.70,8,2006,1,0,0
56,57,4.50,4.50,50,2018,1,0,0
57,58,4.17,4.13,72,2017,1,0,0
58,59,4.14,4.17,36,2015,1,0,0
59,60,4.50,4.25,2,2005,1,0,0

In [36]:
score=[]
for i in range(0,60,1):
    average_rating=df['average_rating'][i]
    author_rating=df['author_rating'][i]
    ratings_count=df['ratings_count'][i]
    year=df['year'][i]
    edition=df['edition'][i]
    impressions=df['impressions'][i]
    clicks=df['clicks'][i]
    
    test_data_values=[average_rating,author_rating,ratings_count,year,edition,impressions,clicks]
    test_data=np.array(test_data_values,ndmin=2)
    value=model2.predict(test_data)
    
    score.append(value[0][0])

In [37]:
df['score']=score
df

,id,isbn,isbn13,name,num_pages,language,genre,edition,year,author,author_rating,average_rating,ratings_count,impressions,clicks,level,score
0,1,1597496553,9781597496551,The Basics of Hacking and Penetration Testing:...,159,english,ethical hacking,1,2011,Patrick Engebretson,3.94,3.92,670,0,0,beginner,0.335306
1,2,521880378,9780521880374,Advanced Data Structures,456,english,data structures,1,2008,Peter Brass,4.29,4.26,27,0,0,advanced,0.299309
2,3,3,3,"Data Structures, Automation & Problem Solving,...",135,english,data structures,1,2015,R.M.Z. Trigo,3.03,3.33,12,0,0,intermediate,0.212905
3,4,4,4,Python & Algorithms 2.0 A Guide to Learn how t...,244,english,python,2,2014,Marina Wahl,3.00,3.00,1,0,0,beginner,0.236740
4,5,1484237323,9781484237328,Applied Natural Language Processing with Pytho...,158,english,machine learning,1,2018,Taweh Beysolow II,2.83,3.50,17,0,0,intermediate,0.212466
5,6,1484225406,9781484225400,Beginning Ethical Hacking with Python,197,english,ethical hacking,1,2017,Sanjib Sinha,2.67,2.27,45,0,0,beginner,0.160840
6,7,1118891457,9781118891452,Beginning Programming with Python for Dummies,411,english,python,1,2014,John Paul Mueller,3.58,3.61,32,0,0,beginner,0.247184
7,8,1788835212,9781788835213,C++ Data Structures and Algorithms: Learn how ...,391,english,data structures,1,2018,Wisnu Anggoro,3.29,3.00,91,0,0,intermediate,0.218123
8,9,1904811302,9781904811305,Creating Your MySQL Database: Practical Design...,105,english,database,1,2006,Marc DeLisle,3.66,3.30,10,0,0,intermediate,0.235401
9,10,1976503302,9781976503306,Data Structures & Algorithms In Go,666,english,data structures,1,2017,Hemant Jain,4.25,3.67,6,0,0,advanced,0.273403
10,11,11,11,Data Structures and Algorithms,19,english,data structures,1,2016,tutorialsPoint,4.50,4.50,100,0,0,beginner,0.324656
11,12,486172627,9780486172620,Data Structures and Algorithm Analysis in C++,613,english,data structures,3,2011,Clifford A. Shaffer,3.76,3.71,7,0,0,intermediate,0.333527
12,13,201498405,9780201498400,Data Structures and Algorithm Analysis in C,570,english,data structures,2,1996,Mark Allen Weiss,3.77,3.86,126,0,0,beginner,0.311097
13,14,486485811,9780486485812,Data Structures and Algorithm Analysis in Java,601,english,data structures,3,2011,Clifford A. Shaffer,3.76,4.00,15,0,0,intermediate,0.345630
14,15,1118290275,9781118290279,Data Structures and Algorithms in Python,770,english,data structures,1,2013,Michael T. Goodrich,3.92,4.09,99,0,0,advanced,0.285653
15,16,1942878486,9781942878483,Data Structures and Algorithms in Swift,328,english,data structures,1,2018,Kelvin Lau,4.26,4.09,11,0,0,beginner,0.290762
16,17,17,17,Data structures and Algorithms using Java,290,english,data structures,1,2014,OReilly Media,4.50,4.50,100,0,0,advanced,0.324492
17,18,521670152,9780521670159,Data Structures and Algorithms Using C#,366,english,data structures,1,2007,Michael McMillan,3.78,3.11,19,0,0,intermediate,0.233629
18,19,8176567418,9788176567411,Data Structures Through C In Depth,272,english,data structures,2,2011,Deepali Srivastava,4.13,4.13,732,0,0,advanced,0.396017
19,20,470618299,9780470618295,Data Structures and Algorithms Using Python,540,english,data structures,1,2010,Rance D. Necaise,4.02,3.81,21,0,0,advanced,0.270774
20,21,321541405,9780321541406,Data Structures and Problem Solving Using Java,949,english,data structures,4,2014,Mark Allen Weiss,3.77,3.52,29,0,0,beginner,0.367937
21,22,619159073,9780619159078,Data Structures Using C++,945,english,data structures,2,2003,D.S. Malik,4.00,4.04,97,0,0,intermediate,0.324855
22,23,23,23,Data Structure with C in hindi,51,hindi,data structures,1,2011,Kuldeep Chand Agnihotri,4.28,3.50,3,0,0,beginner,0.267151
23,24,24,24,Database management system tutorial,80,english,data structures,1,2016,tutorialsPoint,4.50,4.50,100,0,0,beginner,0.324656
24,25,471738840,9780471738848,Data Structures and Algorithms in Java,738,english,data structures,6,2005,Michael T. Goodrich,3.92,3.83,254,0,0,advanced,0.483641
25,26,26,26,Ethical Hacking: Research and Course Compilation,49,english,ethical hacking,1,2016,Ida Matero,3.50,3.50,10,0,0,beginner,0.237784
26,27,27,27,Ethical Hacking,92,english,ethical hacking,1,2018,tutorialsPoint,4.50,4.50,100,0,0,advanced,0.324820
27,28,8193296028,9788193296028,Fundamentals of Data Structures,502,english,data structures,1,2016,Ellis Horowitz,3.84,3.84,390,0,0,intermediate,0.301388
28,29,29,29,Hacking: The Ultimate Guide for You to Learn t...,153,english,ethical hacking,1,2015,Emily Goldstein,2.91,3.25,4,0,0,advanced,0.204315
29,30,133024415,9780133024418,Hands-On Database: An Introduction to Database...,214,english,database,1,2012,Steve Conger,3.40,3.38,16,0,0,intermediate,0.229450
30,31,1719528403,9781719528405,Machine Learning: Step-by-Step Guide To Implem...,103,english,machine learning,1,2018,Rudolph Russell,3.29,1.00,1,0,0,advanced,0.131258
31,32,1484228650,9781484228654,Mastering Machine Learning with Python in Six ...,374,english,machine learning,1,2017,Manohar Swamynathan,4.00,4.00,13,0,0,intermediate,0.277207
32,33,1484242661,9781484242667,Natural Language Processing Recipes: Unlocking...,253,english,machine learning,1,2019,Akshay Kulkarni,3.00,3.00,2,0,0,beginner,0.198202
33,34,8122418589,9788122418583,Principles Of Data Structures Using C And C++,375,english,data structures,1,2008,Vinu V. Das,3.92,4.00,2,0,0,advanced,0.272271
34,35,1590280539,9781590280539,Problem Solving with Algorithms and Data Struc...,240,english,data structures,1,2013,Bradley N. Miller,3.92,4.07,160,0,0,beginner,0.290820
35,36,1590280539,9781590280539,Problem Solving with Algorithms and Data Struc...,241,english,data structures,2,2013,Bradley N. Miller,3.92,4.07,160,0,0,intermediate,0.329867
36,37,1430232374,9781430232377,Python Algorithms: Mastering Basic Algorithms ...,303,english,python,2,2010,Magnus Lie Hetland,3.94,4.00,98,0,0,advanced,0.321623
37,38,1884777813,9781884777813,Python and Tkinter Programming,684,english,python,1,1999,John E. Grayson,3.50,3.53,15,0,0,advanced,0.238045
38,39,1593276036,9781593276034,"Python Crash Course: A Hands-On, Project-Based...",562,english,python,1,2016,Eric Matthes,4.34,4.34,1290,0,0,beginner,0.428188
39,40,1545479119,9781545479117,Python Programming An In-Depth Guide Into The ...,121,english,python,1,2016,The Code Academy,3.47,3.35,20,0,0,advanced,0.231731
40,41,1598631128,9781598631128,Python Programming for the Absolute Beginner,480,english,python,1,2003,Michael Dawson,3.94,3.90,452,0,0,beginner,0.312612
41,42,1597496553,9781597496551,The Basics of Hacking and Penetration Testing:...,159,english,ethical hacking,2,2013,Patrick Engebretson,3.94,3.92,283,0,0,beginner,0.336784
42,43,1849687226,9781849687225,Oracle Advanced PL/SQL Developer Professional ...,428,english,database,2,2016,Saurabh Gupta,4.31,4.31,35,0,0,beginner,0.342527
43,44,857292986,9780857292988,Introduction to Artificial Intelligence,356,english,artificial intelligence,2,2011,Wolfgang Ertel,3.44,3.41,22,0,0,beginner,0.271733
44,45,1789539463,9781789539462,Python Artificial Intelligence Projects for Be...,155,english,artificial intelligence,1,2018,Joshua Eckroth,4.33,4.33,3,0,0,beginner,0.302086
45,46,1119467659,9781119467656,Artificial Intelligence For Dummies,339,english,artificial intelligence,1,2018,John Paul Mueller,3.58,3.58,57,0,0,intermediate,0.248779
46,47,321204662,9780321204660,Artificial Intelligence: A Guide to Intelligen...,435,english,artificial intelligence,2,2005,Michael Negnevitsky,4.21,4.13,63,0,0,advanced,0.333419
47,48,3319141414,9783319141411,Data Mining: The Textbook,746,english,data science,1,2015,Charu C. Aggarwal,4.07,4.44,16,0,0,beginner,0.297249
48,49,1306772516,9781306772518,"Big Data, Data Mining, and Machine Learning: V...",289,english,machine learning,1,2014,Jared Dean,3.30,3.53,15,0,0,advanced,0.231468
49,50,1449361323,9781449361327,Data Science for Business: What you need to kn...,409,english,data science,1,2013,Foster Provost,4.16,4.16,1752,0,0,intermediate,0.458931
50,51,1521031193,9781521031193,A Level Physics MCQs: Multiple Choice Question...,211,english,physics,1,2017,Arshad Iqbal,3.82,3.82,102,0,0,beginner,0.271827
51,52,52,52,General Knowledge Quiz Book,386,english,general knowledge,1,2014,Capella,4.00,4.00,2,0,0,beginner,0.275888
52,53,1535192976,9781535192972,Python: Practical Python Programming For Begin...,161,english,python,1,2016,Jonathan Yates,3.79,3.50,8,0,0,beginner,0.248914
53,54,1484209591,9781484209592,Python Data Analytics: Data Analysis and Scien...,350,english,python,1,2015,Fabio Nelli,3.45,3.14,7,0,0,beginner,0.221400
54,55,55,55,Object-Oriented Programming (OOP) with Java,3341,english,java,1,2016,Dick Baldwin,4.22,4.20,5,0,0,intermediate,0.292745
55,56,194316173,9780194316170,Oxford Business English Dictionary for Learner...,643,english,english,1,2006,Joseph Noble,4.70,4.63,8,0,0,advanced,0.327750
56,57,1789538670,9781789538670,Hands-On Deep Learning for Images with TensorF...,135,english,machine learning,1,2018,Will Ballard,4.50,4.50,50,0,0,advanced,0.319945
57,58,1465461884,9781465461889,Coding Projects in Python,226,english,python,1,2017,D.K. Publishing,4.13,4.17,72,0,0,beginner,0.294674
58,59,199539537,9780199539536,Oxford Dictionary of Proverbs,625,english,english,1,2015,Jennifer Speake,4.17,4.14,36,0,0,intermediate,0.291390
59,60,816051240,9780816051243,Encyclopedia of Mathematics,577,english,mathematics,1,2005,James Stuart Tanton,4.25,4.50,2,0,0,intermediate,0.304434

In [30]:
df_new

,id,average_rating,author_rating,ratings_count,year,edition,impressions,clicks,score
0,1,3.92,3.94,670,2011,1,0,0,0.335306
1,2,4.26,4.29,27,2008,1,0,0,0.299309
2,3,3.33,3.03,12,2015,1,0,0,0.212905
3,4,3.00,3.00,1,2014,2,0,0,0.236740
4,5,3.50,2.83,17,2018,1,0,0,0.212466
5,6,2.27,2.67,45,2017,1,0,0,0.160840
6,7,3.61,3.58,32,2014,1,0,0,0.247184
7,8,3.00,3.29,91,2018,1,0,0,0.218123
8,9,3.30,3.66,10,2006,1,0,0,0.235401
9,10,3.67,4.25,6,2017,1,0,0,0.273403
10,11,4.50,4.50,100,2016,1,0,0,0.324656
11,12,3.71,3.76,7,2011,3,0,0,0.333527
12,13,3.86,3.77,126,1996,2,0,0,0.311097
13,14,4.00,3.76,15,2011,3,0,0,0.345630
14,15,4.09,3.92,99,2013,1,0,0,0.285653
15,16,4.09,4.26,11,2018,1,0,0,0.290762
16,17,4.50,4.50,100,2014,1,0,0,0.324492
17,18,3.11,3.78,19,2007,1,0,0,0.233629
18,19,4.13,4.13,732,2011,2,0,0,0.396017
19,20,3.81,4.02,21,2010,1,0,0,0.270774
20,21,3.52,3.77,29,2014,4,0,0,0.367937
21,22,4.04,4.00,97,2003,2,0,0,0.324855
22,23,3.50,4.28,3,2011,1,0,0,0.267151
23,24,4.50,4.50,100,2016,1,0,0,0.324656
24,25,3.83,3.92,254,2005,6,0,0,0.483641
25,26,3.50,3.50,10,2016,1,0,0,0.237784
26,27,4.50,4.50,100,2018,1,0,0,0.324820
27,28,3.84,3.84,390,2016,1,0,0,0.301388
28,29,3.25,2.91,4,2015,1,0,0,0.204315
29,30,3.38,3.40,16,2012,1,0,0,0.229450
30,31,1.00,3.29,1,2018,1,0,0,0.131258
31,32,4.00,4.00,13,2017,1,0,0,0.277207
32,33,3.00,3.00,2,2019,1,0,0,0.198202
33,34,4.00,3.92,2,2008,1,0,0,0.272271
34,35,4.07,3.92,160,2013,1,0,0,0.290820
35,36,4.07,3.92,160,2013,2,0,0,0.329867
36,37,4.00,3.94,98,2010,2,0,0,0.321623
37,38,3.53,3.50,15,1999,1,0,0,0.238045
38,39,4.34,4.34,1290,2016,1,0,0,0.428188
39,40,3.35,3.47,20,2016,1,0,0,0.231731
40,41,3.90,3.94,452,2003,1,0,0,0.312612
41,42,3.92,3.94,283,2013,2,0,0,0.336784
42,43,4.31,4.31,35,2016,2,0,0,0.342527
43,44,3.41,3.44,22,2011,2,0,0,0.271733
44,45,4.33,4.33,3,2018,1,0,0,0.302086
45,46,3.58,3.58,57,2018,1,0,0,0.248779
46,47,4.13,4.21,63,2005,2,0,0,0.333419
47,48,4.44,4.07,16,2015,1,0,0,0.297249
48,49,3.53,3.30,15,2014,1,0,0,0.231468
49,50,4.16,4.16,1752,2013,1,0,0,0.458931
50,51,3.82,3.82,102,2017,1,0,0,0.271827
51,52,4.00,4.00,2,2014,1,0,0,0.275888
52,53,3.50,3.79,8,2016,1,0,0,0.248914
53,54,3.14,3.45,7,2015,1,0,0,0.221400
54,55,4.20,4.22,5,2016,1,0,0,0.292745
55,56,4.63,4.70,8,2006,1,0,0,0.327750
56,57,4.50,4.50,50,2018,1,0,0,0.319945
57,58,4.17,4.13,72,2017,1,0,0,0.294674
58,59,4.14,4.17,36,2015,1,0,0,0.291390
59,60,4.50,4.25,2,2005,1,0,0,0.304434

In [38]:
df.to_csv('books_with_scores.csv')

In [39]:
df.to_sql('books_with_scores.sql')

TypeError: to_sql() missing 1 required positional argument: 'con'

In [14]:
average_rating=df['average_rating']
author_rating=df['author_rating']
ratings_count=df['ratings_count']
year=df['year']
edition=df['edition']
impressions=df['impressions']
clicks=df['clicks']

In [15]:
test_data=[average_rating,author_rating,ratings_count,year,edition,impressions,clicks]

In [16]:
model2.predict(test_data)

ValueError: in user code:

    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1462 predict_function  *
        return step_function(self, iterator)
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1445 run_step  **
        outputs = model.predict_step(data)
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1418 predict_step
        return self(x, training=False)
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    /home/mohamedfazil/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:155 assert_input_compatibility
        raise ValueError('Layer ' + layer_name + ' expects ' +

    ValueError: Layer sequential expects 1 inputs, but it received 7 input tensors. Inputs received: [<tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float64>, <tf.Tensor 'ExpandDims_1:0' shape=(None, 1) dtype=float64>, <tf.Tensor 'ExpandDims_2:0' shape=(None, 1) dtype=int64>, <tf.Tensor 'ExpandDims_3:0' shape=(None, 1) dtype=int64>, <tf.Tensor 'ExpandDims_4:0' shape=(None, 1) dtype=int64>, <tf.Tensor 'ExpandDims_5:0' shape=(None, 1) dtype=int64>, <tf.Tensor 'ExpandDims_6:0' shape=(None, 1) dtype=int64>]

In [ ]:
test_data=np.array([3.0,4.0,500,2020,5,550,500],ndmin=2)
model2.predict(test_data)